service: sls-layers
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  environment: ${file(configs.js)}

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  dotenvVars: ${file(configs.js)}

layers:
  PocPrisma:
    path: layers/prisma-layer
  PocNodeModules:
    path: layers/node_modules-layer

functions:
  api:
    handler: src/handler.server
    layers:
      - !Ref PocPrismaLambdaLayer
      - !Ref PocNodeModulesLambdaLayer
    events:
      - httpApi: "*"
